### ISSUE TITLE
Insane amounts of orcs, bandits and guards?

### ISSUE THREAD

**Issue by sranan-mang2** [Rebirth-of-the-Night/ToroQuestRevamped#6]
I was AFK in a superflat world outside of any villages, and when I check on a nearby village there are at least 150 orcs and bandits. A similar thing happened with the guards in another village, in which there seemed to be at least 50 new guards.
![2021-05-04_15 59 13](https://user-images.githubusercontent.com/82239901/117062720-ca88f080-acf1-11eb-853c-8431fddf92f9.png)
![2021-05-04_15 59 26](https://user-images.githubusercontent.com/82239901/117062722-cb218700-acf1-11eb-9bad-34e62a318b17.png)
![2021-05-04_15 59 07](https://user-images.githubusercontent.com/82239901/117062726-cc52b400-acf1-11eb-838e-9acbf0e4feeb.png)

**Comment by bglandolt** [comment]
This happens because of an interaction with how extended days works. Bandits will spawn using the world timer (0-23999). Extended day works by jumping back time a few ticks at certain intervals to give an illusion of "extended" days. Like at tick 1200, extended days will jump back 1 tick for 100 ticks (example) to essentially add 5 seconds of time. The bandits will spawn at certain times of the day / ticks, such as 1200. So with extended days installed, each one of those jump-backs gives a chance for bandits to spawn, which is why so many were spawning in earlier versions of RotN. If you have the latest version of toroquest revamped installed, it should no longer do this.

**Comment by sranan-mang2** [comment]
I'm assuming by "extended days" you mean the mod, but I do not have that mod installed. I was also using the latest release of toroquest revamped (04-12-2021). Should I be using the latest beta instead?

**Comment by bglandolt** [comment]
fixed a while ago, bandits and orcs were set to not despawn when near a player (so you wouldnt see them poof out of existence. Additionally, I did not check how many bandits / orcs were spawned). This means if you were AFK then all these mobs would spawn and not despawn ever. This has been fixed now, and shouldnt occur.
